name: Template - Create Terraform Backend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environmentDisplayName:
        required: true
        type: string
      backendServiceArm:
        required: true
        type: string
      backendAzureRmResourceGroupName:
        required: true
        type: string
      backendAzureRmStorageAccountName:
        required: true
        type: string
      backendAzureRmContainerName:
        required: true
        type: string
      location:
        required: true
        type: string

jobs:
  create-tf-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ inputs.backendServiceArm }}

      - name: Create Resource Group
        run: |
          az group create \
            -n ${{ inputs.backendAzureRmResourceGroupName }} \
            -l ${{ inputs.location }}

      - name: Create Storage Account
        run: |
          az storage account create \
            -g ${{ inputs.backendAzureRmResourceGroupName }} \
            -l ${{ inputs.location }} \
            --name ${{ inputs.backendAzureRmStorageAccountName }} \
            --sku Standard_LRS \
            --encryption-services blob

      - name: Create Storage Container
        run: |
          ACCOUNT_KEY=$(az storage account keys list \
            --resource-group ${{ inputs.backendAzureRmResourceGroupName }} \
            --account-name ${{ inputs.backendAzureRmStorageAccountName }} \
            --query [0].value -o tsv)

          az storage container create \
            --name ${{ inputs.backendAzureRmContainerName }} \
            --account-name ${{ inputs.backendAzureRmStorageAccountName }} \
            --account-key $ACCOUNT_KEY
