# Creates storage account + container
# Add your GitHub Actions workflow steps here
name: Create Terraform Backend
on:
  workflow_dispatch:
jobs:
  create-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Add steps to create storage account and container